---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      # renovate: registryUrl=https://cloudnative-pg.github.io/charts
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      pullPolicy: IfNotPresent
      tag: 1.21.1

