apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Dt2gBK7gtzekAjIXYHkPEM+8+ESLEIFub9qt2g==,iv:Qlj2bzsoxfHQzsw0XRrflHpaEqgcjRUJJatB6Bi4QqE=,tag:tbxhe6UXIoXdF4yMF8jHvA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: vault-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaXZvVFluMmpKN2xQWWMy
            cVVKYXl6emtFYlQ2V0NFVFRKWmRBNVlSMURJCmpQWHBOTXl1QllRVEF5NTQ1RzNV
            c1ljam9keVZ0WVd2WjM0aG5LS3A3SjgKLS0tIG9TVjhjeGhHZVdXWURlV25iNWhq
            bHB4MW13SjBrQk40RERqbXdGTVZ5QlEK/zwD0Kt9TAFORhJo/089VImUFIH70RB5
            jkTY++PMK2j2xiAeVfUdDCoSQ8khrh3UqB/GPYrI+af/S05ZvHqd2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T19:00:27Z"
    mac: ENC[AES256_GCM,data:HHgrWjuBGoedNY+JRnxE6b3lbfAoPpgheQ6OBFdJZXid+MVBrdq7r5hQO2fOoW6pTvGDkHEd1JHiWArFB6JnrFR7SM9CHqzMMiyjRWu7WYWz7pFGOO8kvbVjruXcsRC7EJe12+lbkwufVHrcVEhqEDx1uey0SinUD5NB1y+C8hM=,iv:RC8tIMdPcrOolF8g2TJFegkeFgLCd1WAGd3lkoHkqMM=,tag:8TqFuiFBptxTXOeWCPITfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
