apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: default
spec:
  provider:
    vault:
      server: "http://192.168.1.6:8200"
      path: "kv/cluster"
      version: "v2"
      auth:
        # https://www.vaultproject.io/docs/auth/userpass
        userPass:
          path: "userpass"
          username: "cluster"
          secretRef:
            name: "vault-secret"
            key: "password"
