apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTTExMmlrOXJKaHVXaWxZ
            S3QzVUdUMnkzamYyaldRdm1RME9RR3JsMFJVCmk3ZUJ6ejg4TXhwMXBsRUJVQnpC
            YXQ5WWZIWjBCU3Y2RnFJdG83eElXVkkKLS0tIE9KcmU0Y1MyaHRjZ3FEbXcrRFNn
            Zk1jM0VESUpYRnQ3c3oydWE0WUovZEEKss+Rvxi7/GazUtFWyA5NlKn/XN6ebs6n
            pxWTlABU1vgh+ZtYKf21/mn5qaSsFOUR2R8tnSK44YS2D4/0d1hEoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T21:42:39Z"
    mac: ENC[AES256_GCM,data:gNpU+QMPnxlW7pbTbCF4yLp7M1aXuQH3BFORaoDAiM590uCRt6RxncoL+qxPyhscIn7US5bOzkS86Wi/Xk2a70WVEHv6igs4eBQHD+YHvKx74a87S7UzVDOYxgpLtya5CiW9hhNzNu1dYQyI11cHtN6KyZDPtljuChQRWz6Jw18=,iv:LS20Ee6SMzt8HZD0+tzDJdq2sVNqtS8O8syYDRUSHyg=,tag:WzvBQmlbBEWbXjEl9bZk5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
