apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/iRzHpDwnAuFhMhscpJSYun5rxvbpigA,iv:FZlZRZDOyBc2ZXA2ui9aAQY2DGnl2E4wIEqPYxmsI+U=,tag:wo5Q6zhjRaI+HeHW9cK2MA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TklOdWZWNldHeEd1d3Zw
            Z0FKbXVtTUFJOC9wT3NJSzJvY0RaSXVNZXdBCmd5Uk8wM2cxQXlDNVN0amNmODY4
            cEFlcmxYWmlsclFCcDZHTlN6dFU1ME0KLS0tIHJDa3lVSTJ1UlRmSzduYlF0bnRU
            K0srSFBEbTFTTjd4bmErM21jSXZqTjAKFpOxAz9JQRy7EGXWTXOphN/tSyAU9blW
            vuxv7zJ1mgxX3Uth7uTnFqFHa/VmgjdQhChTgsT8o9n3QtvaBXjkJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-13T21:38:49Z"
    mac: ENC[AES256_GCM,data:Zg3BNJ6vvePoOgR6AGFxLpPxSo0/7bo/VIvk897Ylmvhzupi/11tU57mqkG4pVQH3ujF3dtVT1eE2JvDkwF92gmgtdIFQHZxNB9mbKcBt36Ki59aNNWSshBQEgtClmWeP5P/GjHdGT+Lc5LiM12RlaVi++YPwFB+VZ91xOwTo7A=,iv:DF13za3a/D5muY5SFmKhDZ1EawhoHPwrycJHcU9mA9c=,tag:hMMeF0EB19FxcX6Mk7mv6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
