apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cVDDnVafKqa+PItUfsLkpd2c86qh5pMz,iv:MlN+kj7d058o8tqv2v7781FLC/mAVo40xu1ucq/ctH8=,tag:36Dk8UwO4QIUpJlx/DjQ/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcDlGWmJIWlVWVXY0d2pz
            UEllWHF3YmJUdGI1azhYcE5xYW1GTjRmaEE0CjNsN3hna3g5dVI1eXhEOFNldDBR
            WFl6Q3NwYUxzMHN6dzk1b1RSa3o5TlUKLS0tIExicU42MnRyeVIzeW1hQmx1eW0v
            ZUlKT0Y3ZmxBS2Z3RFdvajZVQWwvNFkKW7ItZ1omdHlScWANymB6ZDY9/33k6VHB
            GXBxf/F3GMf++3R/71RWs1qM7QHcbY/TE9vRkKh6iFQsSwdZLSftXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T19:26:53Z"
    mac: ENC[AES256_GCM,data:kgbIaRncenz95UqSgHWAY5CRArKqyO/etNj39I71z1ljKwjZt4SqfwuUyB4MAHFshBYoXX+ToSX6K6RRO3S5ZWbYY8DLLs9HGMYLogYpXPPIRPy3i75KheS3hrAVNikSQSAALHEpnn2XhLlgBLPts+V3oQB44Ru8YysWbGiek1Q=,iv:ybiVmZEYD4krIaj64wINC7qciiba1apO+6KjwryOM1Q=,tag:rqA3lbS+gLchPnB3ur3NFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
