---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: openebs-jiva-csi-default
              globalMounts:
                - path: /config
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/busybox
              tag: latest@sha256:3d3698b745b0c67ddf2c515650b42955b0bcd123c92060008aae4f4aac1c77b3
              pullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - "cp /tmp/config/recyclarr.yml /config/recyclarr.yml"
        containers:
          main:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 6.0.2
            env:
              TZ: America/New_York
              RADARR_API_KEY: "${SECRET_RADARR_API_KEY}"
              SONARR_API_KEY: "${SECRET_SONARR_API_KEY}"
            resources:
              requests:
                cpu: 5m
                memory: 36M
              limits:
                memory: 128M
    service:
      main:
        enabled: false

    defaultPodOptions:
      podSecurityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      config-file:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        advancedMounts:
          main:
            init-config:
              - path: /tmp/config
                readOnly: true
