---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: sonarr-secret
    creationPolicy: Owner
  data:
    - secretKey: sonarr-api-key
      remoteRef:
        key: kv/cluster/media/sonarr
