apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:r1ZSRGVvG5gr1iZ0Hpzye59wzVXbENBBO3ENYHoTtLZsw1zJPtMQTQ==,iv:ez9ebhHmulkPTAd4tPHspz5dTzo1XFS7EEJxGfQCtww=,tag:EyPvomfjQpavvL0t+KCsIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5akk3YW9OUzJRRzkxU2FO
            UjJFaDZ6OHhBa1JWbHJlTGhyMHdlYTBDdDNjCjh6eTM1WmpQMWtPUjVneERDZjFK
            aFVueUV1cHg1cWxmZFQwL0svYU1xdFEKLS0tIHdpTjB2bmlnSlhLNTA4WXZ3YklX
            OHIzaXhBVmNkT01yTTJlZTQwdHFVd0EKSye/mSXEQ4nzyjwK0PxrY/M1qqTyeshT
            FhLAIkWuRsS5k/VAzBBfeEfWr6mTCXdKXNULgOZnmYBvm1fVcPqUWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T20:52:38Z"
    mac: ENC[AES256_GCM,data:gwfcJvVbI9tOpzh+cE8X3EOaVDRByUidJsVGNPRG/Dm4jb8jgtcDawK64hzjZuYzygrbIvwFhdarOF6mWOq2LlYZ/KOkKNFWduZ1mGU21eymVH0Afiw9v0xn6AkEjk6JEaCFkvosfi98JkrYWPhAHmkmJm//ifTJ81t3iCQQb/c=,iv:DQCfONe6kZT5LXsrkF8irqwLXCpTlYDAYB+8QCMnmwI=,tag:NwMGP6vRMvySj26PD8aZew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
