---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./homepage/ks.yaml
  - ./ghcr-secret.sops.yaml
  - ./external-secrets/ks.yaml
  - ./lldap/ks.yaml
  - ./authelia/ks.yaml
  - ./payload-home/ks.yaml
