---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: lldap-secret
    template:
      engineVersion: v2
      data:
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_KEY_SEED: "{{ .LLDAP_KEY_SEED }}"
        LLDAP_DATABASE_URL: |-
          postgres://{{ .LLDAP_POSTGRES_USER }}:{{ .LLDAP_POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local/lldap
        INIT_POSTGRES_DBNAME: lldap
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .LLDAP_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LLDAP_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
  dataFrom:
    - extract:
        key: kv/cluster/default/lldap
    - extract:
        key: kv/cluster/database/cloudnative-pg
