apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:WW22dpHfz0bAO9Qz,iv:GjpuztzxmgrI6soFsah1307vfC/SCIzhXq49dzzUfPw=,tag:Gd6w2SGYBUL/GmCaArN0uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVk9tVks0WVJLaFk2Z1o1
            VWlQN1R1dFZmOTUwblM0cENFT3FjcmtsNHpzClN1OHM5VHdOSzlTVWlIelk3TklU
            Y1d3Zmd6V3Bqa1g0dWNkRENqcktHL0EKLS0tIEJCOUVKSmdDTGZVYTVxTGc1WC9q
            OXNEWEM5dmJHaFhjcHVSOVZSUTRyaDAKd1ovn9aYfb9PMjfV9V+JXfiF4/uAp1xa
            vyoh4xQAHm9pKLdIa+aU/Fuu2CbYKVqfCxddOsXpL8435OxTl2n4Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-13T21:03:51Z"
    mac: ENC[AES256_GCM,data:cnOdhVXUW7e0jM8oXx9yJwwlQ/pdKKlXb+d9Wx/f0DZsFsHyV1c+d0pC139rj8LiLQRrPhCONj6WC5SEUrrMyvRAu0KdZlxnRSCacUaqVIUuTjrSXExp2nhUR+kMnAqY+YWysCIpWE6vuGcS3M9wVq0FcvsyRJYzKUo2a7LSebE=,iv:TU1GNCPPRYC1GLnrw93NMG6YcsiZ0XLzJfwvZQ6MUp0=,tag:ijd9cDpfTP3ZOXRReUZrsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
