apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:xcQDfYzHaIibfPA/,iv:0lIHw2oAPJQEdbrZqhml0tzjZ7uDn0tLf+29pr17nAg=,tag:B+2LsEtiI1EGxGjHucFECA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVUxhMEZhcHVuNENHakcv
            WDVVemlzWG4wQm5BSUQzSzl6UVFnZXlCdkZVCnpIRm1DTVFxenhPbUszQlRXc2tt
            ZGw4ZVZSZEMxRmZoZnNwNzVvajdOTjgKLS0tIEM3dk8yMXZTZDE2UjVJMVFTaGtr
            RFhycS9vemZmdFFoZWlpYytURGFiWjAKkEW53nbPTl+413sG/Oly4HEiq38ODVNT
            OQaEOL8WRH2bTgsQAy6ln6aVILk6/TxqUd1XM+3BNLuIilEEYbPxQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T14:34:04Z"
    mac: ENC[AES256_GCM,data:uHkA5WurBuz7Pt3Gt3GyP0Zfn4MS1gnsO2RXU9xGp7Lr0Pu29y8Ryt0cGdFzcuHVEECK5bYsoPDukAdQQQXl58RHYXV29Iinrs48CZPniNFvumbucrIZa8DUqdnZ1gEHCzh8r54Liol6HJQWsigQCyUictZoSyuBcA6GtC1db1I=,iv:kApnBg8SIVe7bXTvQNOXgJ5aWjkuxgrhX1/DZ7ptgrY=,tag:6wLaj1CaU+preeo2Bw+URw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
