---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: openebs
      namespace: kube-system
  values:
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.28.2.6151-914ddd2b3
    env:
      TZ: Europe/Warsaw
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "${PLEX_ADDRESS}"
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          nginx.ingress.kubernetes.io/configuration-snippet: |
            location = / {
              if ($http_x_plex_device = ""){
                return 301 $scheme://$host/web/index.html;
              }
            }
        ingressClassName: external
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      media:
        enabled: true
        type: nfs
        mountPath: /media
        server: "${NAS_ADDRESS}"
        path: "${NAS_BASE_URL}/media"
      transcode:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        gpu.intel.com/i915: 1
        memory: 3G
      limits:
        gpu.intel.com/i915: 1
        memory: 4G
