---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zero2prod-cluster
  namespace: default
spec:
  instances: 1

  superuserSecret:
    name: superuser-secret

  bootstrap:
    initdb:
      database: newsletter
      owner: newsletter
      secret:
        name: zero2prod-cluster-secret

  storage:
    size: 1Gi

