---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph
      version: 1.27.1
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
