---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payload-uploads
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-jiva-csi-default
